2024-10-15 21:26:09,561 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Urban-University\Projects\module_12\tests_12_4.py", line 21, in test_run
    rnr1 = Runner(1)
           ^^^^^^^^^
  File "D:\Urban-University\Projects\module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-15 21:26:09,562 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Urban-University\Projects\module_12\tests_12_4.py", line 11, in test_walk
    rnr1 = Runner('r1', -5)
           ^^^^^^^^^^^^^^^^
  File "D:\Urban-University\Projects\module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
